version: "3.9" # optional since v1.27.0

services:
  db:
    container_name: transaction_db_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-somepassword}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB:-dev},test
      PGDATA: /data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres:/data/postgres
      - ./scripts/pg:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - database
    restart: unless-stopped

  api:
    container_name: transaction_api_container
    build:
      context: ./api
      target: dev
    environment:
      DATABASE_URL: postgresql://postgres:somepassword@db:5432/dev
    volumes:
      - ./api:/api
      # Comment line below for host mapping of node_modules
      - cache-node-modules-api:/api/node_modules
    ports:
      - "4000:4000"
    restart: always
    networks:
      - database
    depends_on:
      - db

  ui:
    container_name: transaction_ui_container
    build:
      context: ./ui
      target: dev
    environment: 
      VUE_APP_API_URL: ${API_URL:-http://localhost:4000/}
    volumes:
      - ./ui:/ui
      # Comment line below for host mapping of node_modules
      - cache-node-modules-ui:/ui/node_modules
    ports:
      - "8080:8080"
    restart: always
    networks:
      frontend:
        aliases:
          - transactions-ui-local.com

networks:
  database:
  frontend:

volumes:
  postgres:
  cache-node-modules-api:
  cache-node-modules-ui: